set(FS_ORGANIZATION "Foxxy Soft")
set(CFS_ORGANIZATION "FoxxySoft")
string(TIMESTAMP FS_YEAR %Y)
set(FS_COPYRIGHT "Copyright (C) 2011-${FS_YEAR} ${FS_ORGANIZATION}")

set(FS_VERSION "0.4.4")
string(REPLACE "." "," FS_VERSION_RC ${FS_VERSION})
set(CFS_DATA "FSData")
set(CFS_EDITOR "FSEditor")
set(FS_EDITOR "Foxxy Soft Editor 3D")
set(FS_GITHUB "https://github.com/nelbok/FSEditor3D")
set(FS_DISCORD "https://discord.gg/8xnYPGTxsh")
set(FS_TWITTER "https://twitter.com/bok_nel")
