set(FS_ORGANIZATION "Foxxy Soft")
set(CFS_ORGANIZATION "FoxxySoft")
string(TIMESTAMP FS_YEAR %Y)
set(FS_COPYRIGHT "Copyright (C) 2011-${FS_YEAR} ${FS_ORGANIZATION}")

set(LH_VERSION "0.1.2")
string(REPLACE "." "," LH_VERSION_RC ${LH_VERSION})
set(CLH_DATA "LHData")
set(CLH_EDITOR "LHEditor")
set(LH_EDITOR "LH Editor 3D")
set(LH_GITHUB "https://github.com/nelbok/LHEditor3D")
set(LH_DISCORD "https://discord.gg/8xnYPGTxsh")
set(LH_TWITTER "https://twitter.com/bok_nel")
