name: Linux compilation
on: [push]
jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.*'
          modules: qtquick3d qtquick3dphysics qtshadertools
      - run: cmake -B build
      - run: cmake --build build | tree ${{ github.workspace }}