name: Linux compilation
on: [push]
jobs:
  qt6_6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.*'
          arch: 'gcc_64'
          modules: 'qtquick3d qtquick3dphysics qtshadertools qtquicktimeline'
      - run: cmake -B build
      - run: cmake --build build --config Release
      - run: ./build/tests/tests -platform offscreen
  qt6_8_LTS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.*'
          arch: 'linux_gcc_64'
          modules: 'qtquick3d qtquick3dphysics qtshadertools qtquicktimeline'
      - run: cmake -B build -D FS_SHARED=ON
      - run: cmake --build build --config Release
      - run: ./build/tests/tests -platform offscreen